//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtCreateToken_GUI {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NtCreateToken_GUI.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 请以管理员权限运行！ 的本地化字符串。
        /// </summary>
        internal static string AdminRun {
            get {
                return ResourceManager.GetString("AdminRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有文件 的本地化字符串。
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 即将运行以下命令： 的本地化字符串。
        /// </summary>
        internal static string BeforeRun1 {
            get {
                return ResourceManager.GetString("BeforeRun1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要继续吗？ 的本地化字符串。
        /// </summary>
        internal static string BeforeRun2 {
            get {
                return ResourceManager.GetString("BeforeRun2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是：确定运行。 的本地化字符串。
        /// </summary>
        internal static string BeforeRun3 {
            get {
                return ResourceManager.GetString("BeforeRun3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否：将命令行写入剪贴板，取消运行。 的本地化字符串。
        /// </summary>
        internal static string BeforeRun4 {
            get {
                return ResourceManager.GetString("BeforeRun4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消：取消运行，不做任何事。 的本地化字符串。
        /// </summary>
        internal static string BeforeRun5 {
            get {
                return ResourceManager.GetString("BeforeRun5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请检查参数设置。 的本地化字符串。
        /// </summary>
        internal static string CheckArg {
            get {
                return ResourceManager.GetString("CheckArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择一个 NtCreateToken 配置文件 的本地化字符串。
        /// </summary>
        internal static string ChooseNTCTP {
            get {
                return ResourceManager.GetString("ChooseNTCTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令行已成功复制到剪贴板！ 的本地化字符串。
        /// </summary>
        internal static string CopyCSucc {
            get {
                return ResourceManager.GetString("CopyCSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可执行文件 的本地化字符串。
        /// </summary>
        internal static string ExecutableFile {
            get {
                return ResourceManager.GetString("ExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择一个可执行文件 的本地化字符串。
        /// </summary>
        internal static string ExecutableTitle {
            get {
                return ResourceManager.GetString("ExecutableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 NtCreateToken 配置文件 的本地化字符串。
        /// </summary>
        internal static string ExportP {
            get {
                return ResourceManager.GetString("ExportP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出配置成功！ 的本地化字符串。
        /// </summary>
        internal static string ExportSuc {
            get {
                return ResourceManager.GetString("ExportSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法将命令行复制到剪贴板！ 的本地化字符串。
        /// </summary>
        internal static string FailToCopyC {
            get {
                return ResourceManager.GetString("FailToCopyC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动失败！ 的本地化字符串。
        /// </summary>
        internal static string FailToRun {
            get {
                return ResourceManager.GetString("FailToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到“NtCreateToken.exe”！ 的本地化字符串。
        /// </summary>
        internal static string FileMissing {
            get {
                return ResourceManager.GetString("FileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入配置失败！ 的本地化字符串。
        /// </summary>
        internal static string ImportFail {
            get {
                return ResourceManager.GetString("ImportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入配置成功！ 的本地化字符串。
        /// </summary>
        internal static string ImportSuc {
            get {
                return ResourceManager.GetString("ImportSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NtCreateToken 配置文件 的本地化字符串。
        /// </summary>
        internal static string NTCTP {
            get {
                return ResourceManager.GetString("NTCTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （未知） 的本地化字符串。
        /// </summary>
        internal static string SidUnknown {
            get {
                return ResourceManager.GetString("SidUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功启动！ 的本地化字符串。
        /// </summary>
        internal static string SuccessRun {
            get {
                return ResourceManager.GetString("SuccessRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
